const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let pct=0;const timer=setInterval(()=>{pct+=Math.floor(Math.random()*9)+3;if(pct>=100){pct=100;clearInterval(timer);setTimeout(()=>$('.loader').classList.add('done'),350)}$('.loader b').textContent=pct+'%';$('.loadbar i').style.width=pct+'%'},45);

const header=document.querySelector('header');window.addEventListener('scroll',()=>{header.classList.toggle('scrolled',scrollY>25);document.querySelector('.scrollbar').style.height=(scrollY/(document.body.scrollHeight-innerHeight)*100)+'%'});
const menu=$('#hamb'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{nav.classList.toggle('open');menu.textContent=nav.classList.contains('open')?'×':'☰'});$$('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const theme=$('#theme');theme.onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');

const words=['MODERN WEBSITES','DIGITAL EXPERIENCES','DATABASE SYSTEMS','CREATIVE CODE'];let wi=0,ci=0,del=false;function typing(){const el=$('#typed'),w=words[wi];el.textContent=del?w.slice(0,ci--):w.slice(0,ci++);if(!del&&ci>w.length){del=true;return setTimeout(typing,1100)}if(del&&ci<0){del=false;wi=(wi+1)%words.length;ci=0}setTimeout(typing,del?40:75)}setTimeout(typing,700);

const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');if(e.target.classList.contains('skill'))e.target.style.setProperty('--p',e.target.dataset.p+'%')}}),{threshold:.12});$$('.reveal').forEach(x=>obs.observe(x));
const data={bookmart:['01 / WEB + DATABASE','CBI BOOKMART','Website toko buku dengan PHP dan MySQL, termasuk CRUD, kategori, pesanan dan detail pesanan.',['PHP','MYSQL','CRUD']],python:['02 / CODE','STUDENT DATA','Program Python untuk mengolah daftar nilai, loop, percabangan, predikat dan rata-rata.',['PYTHON','LIST','LOOP']],portfolio:['03 / FRONT-END','PORTFOLIO SYSTEM','Portfolio personal interaktif dengan responsive layout, animasi, filter project dan theme switcher.',['HTML','CSS','JAVASCRIPT']],database:['04 / DATABASE','DATA ARCHITECTURE','Konsep relasi database dengan primary key dan foreign key untuk aplikasi berbasis data.',['MYSQL','SQL','RELATION']]};
const modal=$('#modal');$$('.work').forEach(card=>card.onclick=()=>{let d=data[card.dataset.id];$('#mcat').textContent=d[0];$('#mtitle').textContent=d[1];$('#mdesc').textContent=d[2];$('#mtech').innerHTML=d[3].map(x=>`<span>${x}</span>`).join('');modal.classList.add('open')});function close(){modal.classList.remove('open')}$('#close').onclick=close;$('.backdrop').onclick=close;document.onkeydown=e=>e.key==='Escape'&&close();
$$('.filter-row button').forEach(btn=>btn.onclick=()=>{$$('.filter-row button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');let f=btn.dataset.filter;$$('.work').forEach(c=>c.classList.toggle('hide',f!=='all'&&!c.dataset.cat.includes(f)))});
const dot=$('.cursor'),ring=$('.cursor-ring');let mx=0,my=0,rx=0,ry=0;addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY;dot.style.left=mx+'px';dot.style.top=my+'px'});function cur(){rx+=(mx-rx)*.17;ry+=(my-ry)*.17;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(cur)}cur();$$('a,button,.work').forEach(x=>{x.onmouseenter=()=>{ring.style.width='55px';ring.style.height='55px'};x.onmouseleave=()=>{ring.style.width='34px';ring.style.height='34px'}});
$$('.tilt').forEach(c=>{c.onmousemove=e=>{let r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;c.style.transform=`perspective(800px) rotateY(${x*10}deg) rotateX(${-y*10}deg) rotateZ(2deg)`};c.onmouseleave=()=>c.style.transform='rotate(2deg)'});
const canvas=$('#stars'),ctx=canvas.getContext('2d');let ps=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);for(let i=0;i<70;i++)ps.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.18,vy:(Math.random()-.5)*.18,r:Math.random()*1.2});function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=document.body.classList.contains('light')?'rgba(0,0,0,.25)':'rgba(255,255,255,.3)';ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>canvas.width)p.vx*=-1;if(p.y<0||p.y>canvas.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(draw)}draw();
const sections=[...document.querySelectorAll('section[id]')];addEventListener('scroll',()=>{let id='home';sections.forEach(s=>{if(scrollY>s.offsetTop-180)id=s.id});$$('nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+id))});
$$('[data-n]').forEach(el=>{let target=+el.dataset.n;let o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!e.target.dataset.done){e.target.dataset.done=1;let n=0;let t=setInterval(()=>{n++;e.target.textContent=n;if(n>=target)clearInterval(t)},35)}}));o.observe(el)});
$('#year').textContent=new Date().getFullYear();
